**Завдання 1**

In [2]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np

a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
import numpy as np

a = np.random.randint(1, 10, (5, 5))
print(a)


[[5 6 6 2 7]
 [9 2 4 3 3]
 [1 3 6 5 1]
 [6 3 6 8 2]
 [9 2 8 8 4]]


In [15]:
import numpy as np

a = np.random.random((4, 4))
print(a)

[[0.93254842 0.86485245 0.35488663 0.46896036]
 [0.93749522 0.85834757 0.24412366 0.41697934]
 [0.99428751 0.87839467 0.19451621 0.91328282]
 [0.5776297  0.6708447  0.61571907 0.53481441]]


In [17]:
import numpy as np

a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[9 2 1 2 7]
[8 4 3 7 9]
[17  6  4  9 16]
[ 1 -2 -2 -5 -2]
[72  8  3 14 63]


In [18]:
import numpy as np

a = np.random.randint(1, 10, 7)
b = np.random.randint(1, 10, 7)
print(a)
print(b)
print(np.dot(a, b))

[7 2 9 7 5 3 1]
[4 8 2 1 3 4 9]
105


In [20]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)
print(np.dot(a, b))

[[7 4]
 [4 1]]
[[5 5 6]
 [6 4 5]]
[[59 51 62]
 [26 24 29]]


In [22]:
import numpy as np

a = np.random.randint(1, 10, (3, 3))
b = np.linalg.inv(a)
print(a)
print(b)

[[2 3 3]
 [5 4 9]
 [1 2 2]]
[[ 2.0000000e+00  8.8817842e-17 -3.0000000e+00]
 [ 2.0000000e-01 -2.0000000e-01  6.0000000e-01]
 [-1.2000000e+00  2.0000000e-01  1.4000000e+00]]


In [24]:
import numpy as np

a = np.random.random((4, 4))
b = a.T
print(a)
print(b)

[[0.42560354 0.63158381 0.58147567 0.64541952]
 [0.03010295 0.26043955 0.83447824 0.56149815]
 [0.16110098 0.6869734  0.32520669 0.41553119]
 [0.16864349 0.34918595 0.63650406 0.45396779]]
[[0.42560354 0.03010295 0.16110098 0.16864349]
 [0.63158381 0.26043955 0.6869734  0.34918595]
 [0.58147567 0.83447824 0.32520669 0.63650406]
 [0.64541952 0.56149815 0.41553119 0.45396779]]


In [25]:
import numpy as np

a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, 4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[7 8 2 3]
 [1 8 9 6]
 [8 7 7 1]]
[5 1 1 6]
[63 58 60]


In [26]:
import numpy as np

a = np.random.random((2, 3))
b = np.random.random(3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[0.72714219 0.6262278  0.35521783]
 [0.67897538 0.6248451  0.21296304]]
[0.30116547 0.79796592 0.38683788]
[0.85611027 0.7854712 ]


In [28]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a)
print(b)
print(a * b)

[[3 1]
 [7 7]]
[[2 4]
 [8 2]]
[[ 6  4]
 [56 14]]


In [29]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[4 5]
 [3 2]]
[[3 9]
 [4 5]]
[[32 61]
 [17 37]]


In [30]:
import numpy as np

a = np.random.randint(1, 100, (5, 5))
print(a)
print(np.sum(a))

[[79 42 46 86 71]
 [98 82 13 44 52]
 [38 78 60 91 49]
 [40  6 22 34 50]
 [77 45 60 43 11]]
1317


In [31]:
import numpy as np

a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a)
print(b)
print(a - b)

[[3 1 5 1]
 [6 5 6 5]
 [1 5 1 7]
 [4 5 7 3]]
[[5 4 7 4]
 [6 9 5 2]
 [6 6 6 8]
 [4 8 4 3]]
[[-2 -3 -2 -3]
 [ 0 -4  1  3]
 [-5 -1 -5 -1]
 [ 0 -3  3  0]]


In [35]:
import numpy as np

a = np.random.random((3, 3))
b = a.sum(axis=1)
print(a)
print(b)

[[0.17270524 0.0986174  0.30641645]
 [0.71174185 0.41733905 0.62467129]
 [0.88094037 0.92511932 0.46840829]]
[0.57773909 1.7537522  2.27446798]


In [32]:
import numpy as np

a = np.random.randint(1, 10, (3, 4))
b = a **2
print(a)
print(b)

[[9 2 5 5]
 [1 9 8 7]
 [1 2 5 1]]
[[81  4 25 25]
 [ 1 81 64 49]
 [ 1  4 25  1]]


In [34]:
import numpy as np

a = np.random.randint(1, 50, 4)
b = np.sqrt(a)
print(a)
print(b)

[29 12 39 32]
[5.38516481 3.46410162 6.244998   5.65685425]


**Завдання 2 - Додаткове**

In [37]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.where(arr%2 != 0, -1, arr)
print(b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [38]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = arr.reshape(2, -1)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
import numpy as np

#3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
# Не зовсім зрозумів що треба зробити, можзиво щось таке:

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
c = np.vstack((a, b))
print(a)
print(b)
print(c)

[[4 1]
 [3 2]]
[[5 2]
 [9 6]]
[[4 1]
 [3 2]
 [5 2]
 [9 6]]


In [43]:
import numpy as np

a = np.array([1, 2, 3])

b = np.repeat(a, 3)
c = np.tile(a, 3)
res = np.concatenate([b, c])

print(a)
print(res)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [44]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res = np.intersect1d(a, b)
print(res)

[2 4]


In [48]:
import numpy as np

a = np.random.uniform(1,50, 20)

res = (np.partition(a, -5)[-5:])[::-1]
print(a)
print(res)

[37.38150477 31.87901289 29.51026743  2.00151747 11.29130231 27.68955903
 38.68664338 13.28406623 15.00888883 42.7673593  48.77531819 44.35781138
 18.61588435 30.34408835 18.38498497 17.66932055  9.72596849 12.64701622
  3.19825184 25.76614005]
[48.77531819 44.35781138 42.7673593  38.68664338 37.38150477]


In [60]:
import numpy as np

a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

print(a)
res = a[~np.isnan(a)]
print(res)



[ 1.  2.  3. nan  5.  6.  7. nan]
[1. 2. 3. 5. 6. 7.]


In [61]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

res = np.linalg.norm(a -b)
print(res)

6.708203932499369


In [66]:
import numpy as np

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

res = np.where(x == 1)[0]
print(res[4])

8


In [70]:
import numpy as np

a = np.random.randint(0, 5, 10)
print(a)

_, ixs = np.unique(a, return_index=True)
res = np.ones(a.size, dtype=bool)
res[ixs] = False
print(res)

[3 0 4 2 4 3 4 4 2 0]
[False False False False  True  True  True  True  True  True]
